# Generated by Django 3.2.13 on 2022-07-17 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model_name', models.CharField(max_length=255)),
                ('vehicle_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='vehicles.vehiclemake')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('chasis_number', models.CharField(max_length=255)),
                ('registration_year', models.PositiveSmallIntegerField()),
                ('registration_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('manufacture_year', models.PositiveSmallIntegerField()),
                ('manufacture_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('vehicle_model_code', models.CharField(max_length=255)),
                ('engine_size', models.PositiveSmallIntegerField()),
                ('exterior_color', models.CharField(choices=[('BEIGE', 'Beige'), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('BRONZE', 'Bronze'), ('BROWN', 'Brown'), ('GOLD', 'Gold'), ('GRAY', 'Gray'), ('GREEN', 'Green'), ('MAROON', 'Maroon'), ('ORANGE', 'Orange'), ('PEARL', 'Pearl'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('SILVER', 'Silver'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=50)),
                ('fuel', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID_DIESEL', 'Hybrid (Diesel)'), ('HYBRID_PETROL', 'Hybrid (Petrol)'), ('CNG', 'CNG'), ('PLG', 'PLG'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=50)),
                ('transmission', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('CVT', 'CVT'), ('DCT', 'DCT'), ('MANUAL', 'Manual'), ('SEMI_AUTOMATIC', 'Semi Automatic'), ('SPORT_AT', 'Sport AT'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=50)),
                ('body_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV'), ('MINI_VAN', 'Mini Van'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('WAGON', 'Wagon'), ('COUPE', 'Coupe'), ('MINI_VEHICLE', 'Mini Vehicle'), ('BUS', 'Bus'), ('MINI_BUS', 'Mini Bus'), ('PICKUP', 'Pick up'), ('CONVERTIBLE', 'Convertible'), ('MOTORCYCLE', 'Motorcycle'), ('TRACTOR', 'Tractor'), ('MACHINERY', 'Machinery'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=50)),
                ('drive_train', models.CharField(choices=[('TWO_WHEEL_DRIVE', '2 Wheel Drive'), ('FOUR_WHEEL_DRIVE', '4 Wheel Drive'), ('ALL_WHEEL_DRIVE', 'All Wheel Drive'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=50)),
                ('steering', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=50)),
                ('country_of_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.country')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.vehiclemodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('registration_year__gte', 1950), ('registration_year__lte', 2022)), name='registration_year_between_1950_and_current_year'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('registration_month__gte', 1), ('registration_month__lte', 12)), name='registration_month_between_1_and_12'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('manufacture_year__gte', 1950), ('manufacture_year__lte', 2022)), name='manufacture_year_between_1950_and_current_year'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('manufacture_month__gte', 1), ('manufacture_month__lte', 12)), name='manufacture_month_between_1_and_12'),
        ),
    ]
