# Generated by Django 3.2.13 on 2022-07-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('vehicles', '0002_vehicle_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='country_of_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='setup.country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
