# Generated by Django 3.2.13 on 2022-07-24 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_removed'),
        ('vehicles', '0003_delete_country_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehice_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehice_images', to='files.file'),
        ),
    ]
