# Generated by Django 3.2.13 on 2022-07-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_removed'),
        ('vehicles', '0004_add_image_to_vehicle_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehice_image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_images', to='files.file'),
        ),
    ]
