# Generated by Django 3.2.13 on 2022-08-07 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_removed'),
        ('vehicles', '0005_modify_vehicle_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemake',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_makes', to='files.file'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_modelss', to='files.file'),
        ),
    ]
