# Generated by Django 3.2.13 on 2022-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_randommodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='randommodel',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
