# Generated by Django 3.2.13 on 2022-08-06 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_file_removed'),
        ('vehicles', '0005_modify_vehicle_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparepart_category_images', to='files.file')),
                ('relates_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareparts.sparepartcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='spareparts.sparepartcategory')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='files.file')),
                ('vehicle_models', models.ManyToManyField(blank=True, null=True, related_name='spare_parts', to='vehicles.VehicleModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
