# Generated by Django 3.2.13 on 2022-08-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
