# Generated by Django 3.2.13 on 2022-08-08 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('suppliers', '0002_add_super_base_model_to_supplier_model'),
        ('spareparts', '0002_alter_sparepart_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_purchases', to='employee.employee')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_purchases', to='spareparts.sparepart')),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_purchases', to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
