# Generated by Django 3.2.13 on 2022-08-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0003_add_sparepart_purchase_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepart',
            options={'permissions': (('view_dashboard', 'Can view dashboard'), ('view_setup', 'Can view setup'))},
        ),
    ]
